site_name: mkdocs.balloon.net.eu.org
site_url: https://mkdocs.balloon.net.eu.org/
repo_url: https://github.com/fu-sen/mkdocs.balloon.net.eu.org
repo_name: <i class="fa-brands fa-github"></i> GitHub ã‚½ãƒ¼ã‚¹
edit_uri: ""
copyright: Maked by <a href="https://balloon.asia/">ãµã†ã›ã‚“ğŸˆ FU-SEN</a>

theme:
    name: cosmo
    locale: ja
    custom_dir: custom/

extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css

plugins:
    - search:
        min_search_length: 1
